version: '3.9'

services:
  tsurei:
    container_name: tsurei
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./tsurei:/tsurei:Z
      - ./tsurei/tsurei/static/:/tsurei/tsurei/static/
      - ./tsurei/tsurei/uploads/:/tsurei/tsurei/uploads/
    env_file:
      - ./tsurei/tsurei/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data:/var/lib/postgresql/data:z
    env_file:
      - ./tsurei/tsurei/.env
